
export const projects = [
    {
        id: 1,
        title: "MicroplasticsMacroproblems",
        tagline: "Catch oxigen bubble in a polluted ocean",
        img: require("./img/Microplastics.jpg"),
        link: "https://guillemfd.github.io/P1---MicroplasticsMacroproblem/",
        github: "https://github.com/guillemfd/P1---MicroplasticsMacroproblem",
        description: `You are a fish swimming in an ocean full of microplastics, you will inevitably die after 30"... At least, do your best to live as oxygenated as possible by catching plenty of pure O2 bubbles!`,
        techs: require("./img/techs-MM.png"),
    },
    {
        id: 2,
        title: "Pick6Pics",
        tagline: "Select your favorite pic of each continet",
        img: require("./img/Pick6Pics.jpg"),
        link: "https://pick-6-pics.herokuapp.com/",
        github: "https://github.com/guillemfd/P2---pick_6_pics",
        description: "Pick 6 pics!, one from each continent. Here we are using the unsplash API, a huge and free photo database. First you will be requested to SignUp or LogIn. Then you can click on a continent, pick your favorite pic of each one and see all them together in your profile.",
        techs: require("./img/techs-Pick6Pics.png"),
    },
    {
        id: 3,
        title: "swapp",
        tagline: "Swapp products with other users",
        img: require("./img/swapp.jpg"),
        link: "https://www.linkedin.com/in/guillemfd/",
        github: "https://github.com/IronhackFinalProject/swapp-project",
        description: "Join the community and start swapping your items with other users. Upload your products, put others in your favorites list, sort them by categories and negotiate with other users.",
        techs: require("./img/techs-swapp.png"),
    },
    {
        id: 4,
        title: "TV2C",
        tagline: "Search movies&series and make your lists",
        img: require("./img/TV2C.jpg"),
        link: "https://www.linkedin.com/in/guillemfd/",
        github: "https://github.com/guillemfd/TV2C",
        description: `Sort movies & TV Series by plenty of preloaded searches, create personalised lists, update your "To See List" or just look for new movies and check all its data. Special thanks to TMDB API!`,
        techs: require("./img/techs-TV2C.png"),
    },
    {
        id: 5,
        title: "Portfolio",
        tagline: "To get to know me a little better",
        img: require("./img/portfoli.jpg"),
        link: "https://www.guillemfd.com/",
        github: "https://github.com/guillemfd/Portfolio",
        description: "To get to know me a little better", 
        techs: require("./img/techs-portfolio.png"),
    },
]

export const galleries = [
    {
        id: 1,
        title: "Architect's office",
        img: require("./img/GalleryOne/MiniGeensen-3.jpg"),
        link: "/GalleryOne",
    },
    {
        id: 2,
        title: "Home in Barcelona (living area)",
        img: require("./img/GalleryTwo/living/L- (9).jpg"),
        link: "/GalleryTwo",
    },
    {
        id: 3,
        title: "Home in Barcelona (convenience areas)",
        img: require("./img/GalleryTwo/outdoors/O- (11).jpg"),
        link: "/GalleryThree",
    },
    {
        id: 4,
        img: "https://payload.cargocollective.com/1/3/108763/1398170/_MG_8543.png",
        link: "https://cargocollective.com/guillemfd/malawi-postes-de-sol",
    },
    {
        id: 5,
        img: "https://payload.cargocollective.com/1/3/108763/1398170/_MG_8543.png",
        link: "https://cargocollective.com/guillemfd/malawi-postes-de-sol",
    },
    {
        id: 6,
        img: "https://payload.cargocollective.com/1/3/108763/1397744/_MG_6883.jpg",
        link: "https://cargocollective.com/guillemfd/malawi-miscelania",
    },
    {
        id: 7,
        img: "https://payload.cargocollective.com/1/3/108763/1398275/IMG_3961.JPG",
        link: "https://cargocollective.com/guillemfd/escenes",
    },
]

export const referrals = [
    {
        id: 1,
        link: "https://ie.linkedin.com/in/sam-warbrick",
        img: require("./img/referrals/sam.jpg"),
        name: "Sam Warbrick",
        country: "Ireland",
        position: "Conference & Event Manager",
        referral: "I have had the pleasure of collaborating with Guillem on several projects in recent years, each executed with the utmost professionalism, accuracy and efficiency.",
        referralB: "No request was ever too much - which resulted in very positive and successful projects.",
    },
    {
        id: 2,
        link: "https://de.linkedin.com/in/jonas-b%C3%B6lte-505694153",
        img: require("./img/referrals/jonas.jpg"),
        name: "Jonas Bölte",
        country: "Germany",
        position: "Marketing Manager bei COMPRION",
        referral: "Guillem and I have had the pleasure of working together on a number of projects over the past years. Not only is he highly professional, but he is also very solution oriented and always strives to exceed all requirements.",
        referralB: "You couldn't ask for a better project partner.",
    },
    {
        id: 3,
        link: "https://www.linkedin.com/in/fer-full-stack/",
        img: require("./img/referrals/fer.jpg"),
        name: "Fernando O.",
        country: "Spain",
        position: "Senior Product Manager and Jr Front end Developer. Web3 passionate & UX lover",
        referral: "He's a tireless researcher for the best solution possible to any problem we faced during the development of different REACT projects. Very creative, UX aware and with a Product approach to every step we made.",
        referralB: "Guillem is pure talent in the Back end and a high skilled Front end developer. I wish we can work together again and I'm very sure he'll be a very valuable asset to any team he work in.",
    },
    {
        id: 4,
        link: "https://uk.linkedin.com/in/balvinder-sandhu-23a674a6",
        img: require("./img/referrals/bal.jpg"),
        name: "Balvinder Sandhu",
        country: "United Kingdom",
        position: "Marketing Manager at Enghouse Networks",
        referral: "Genuine expert is the phrase that comes to mind when I think about Guillem. I had the pleasure of working with Guillem for many years. His ability to handle multiple projects and always provide a professional service under pressure was amazing. He never said no and always had a solution to any situations that arose.",
        referralB: "Any employee would be lucky to have a hard working and dedicated team player as Guillem on their team.",
    },
    {
        id: 5,
        link: "https://es.linkedin.com/in/annasolerjuve",
        img: require("./img/referrals/anna.jpg"),
        name: "Anna Soler",
        country: "Spain",
        position: "Marketing and Events specialist",
        referral: "He tenido la gran suerte y el placer de haber sido compañera de trabajo de Guillem. Decir que es una persona que se desvive por el trabajo impecable, perfecionista, entregado pero sobretodo es un gran compañero dispuesto ayudar a los demás siempre que lo necesitáramos.",
        referralB: "La verdad que cuesta encontrar personas como él en las que trabajar en equipo todo se convierte en éxitos. Sin duda un gran profesional.",
    },
    {
        id: 6,
        link: "https://se.linkedin.com/in/fernandocases94",
        img: require("./img/referrals/nando.jpg"),
        name: "Fernando Cases",
        country: "Sweden",
        position: "Jr FrontEnd Developer",
        referral: "He's very talented, proactive and an expert problem solver with high dosis of creativity.",
    },
]
